/*
Index usage statistics
*/
SELECT
	OBJECT_NAME(S.[OBJECT_ID]) as [OBJECT NAME]
	,I.[NAME] AS [INDEX NAME]
	,USER_SEEKS
	,USER_SCANS
	,USER_LOOKUPS
	,USER_UPDATES 
FROM SYS.DM_DB_INDEX_USAGE_STATS AS S
INNER JOIN SYS.INDEXES AS I ON I.[OBJECT_ID] = S.[OBJECT_ID] AND I.INDEX_ID = S.INDEX_ID 
order by USER_SEEKS desc

